In [1]:
import numpy as np
import schelling_model as sm

# Create a numpy matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Set print options for numpy
np.set_printoptions(precision=2, suppress=True, linewidth=100)

# Print the matrix
print("Fancy representation of the matrix:")
print(matrix)

Fancy representation of the matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
Kernel = np.array([[1,1,1],[1,0,1],[1,1,1]],dtype=np.int8)
Kernel2 = np.array([[2,-2],[2,-1],[2,0],[2,1],[2,2],[1,-2],[1,-1],[1,0],[1,1],[1,2],[0,-2],[0,-1],[0,0],[0,1],[0,2],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2]\
    ,[-2,-2],[-2,-1],[-2,0],[-2,1],[-2,2]])
model = sm.ClassicSchellingModel(20,0.6,0.001,1,Kernel,0.00001)
model = model.rand_init()

In [9]:
model.print_matrix() 

[[ 1  1  0  1  0  0  1  0  1  0  1  1  0  0  1  0  1  1  1  1]
 [ 1  0  1  0  1  0  1  0  0  1  0  0  1  1  1  1  0  0  0  1]
 [ 1  1  1  1  0  0  0  1  0  0  1  1  0  1  1  0  1  1  1  1]
 [ 0  0  1  1  1  1  1  0  1  1  0  1  0  0  0  0  0  0  0  0]
 [ 0  1  1  0  1  0  0  1  1  1  1  0  1  0  0  1  0  0  0  0]
 [ 0  0  1  1  0  0  1  0  0  1  1  1  1  0  1  1  1  0  0  1]
 [ 0  0  1  1  1  1  0  1  0  1  0  0  1  1  0  1  0  0  1  1]
 [ 1  1  1  0  0  0  0  1  1  1  0  1  1  0  1  0  0  1  0  1]
 [ 0  1  1  1  1  0  0  0  0  0  0  0  0 -1  0  0  0  0  1  1]
 [ 1  0  0  1  1  1  1  1  0  0  0  1  0  1  0  0  1  1  1  0]
 [ 0  0  1  0  0  0  1  0  0  1  1  0  1  0  0  0  0  0  1  1]
 [ 0  0  0  1  1  1  0  1  0  0  0  0  0  0  0  1  1  0 -1  0]
 [ 1  1  0  1  0  0  0  0  0  1  0  1  0  1  0  0  0  0  1  1]
 [ 1  0  0  1  1  0  1  0  1  1  1  1  0  1  1  1  1  0  0  0]
 [ 0  1  1  0  1  1  0  1  0  0  1  1  1  0  0  1  1  0  1  0]
 [ 0  0  0 -1  1  1  1  1  1  1  1  0  1  0  1  0  1  1