In [1]:
import numpy as np
import schelling_model as sm

In [2]:
Kernel = np.array([[1,1,1],[1,0,1],[1,1,1]],dtype=np.int8)
Kernel2 = np.array([[2,-2],[2,-1],[2,0],[2,1],[2,2],[1,-2],[1,-1],[1,0],[1,1],[1,2],[0,-2],[0,-1],[0,0],[0,1],[0,2],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2]\
    ,[-2,-2],[-2,-1],[-2,0],[-2,1],[-2,2]])
model = sm.ClassicSchellingModel(20,0.6,0.01,1,Kernel,0.00001)
model = model.rand_init()

In [3]:
model.print_matrix() 
m1 = model.get_matrix()

[[ 1  0  0  0  0  0  1  0  1  0  1  1  0  1  0  1  0  1  1  1]
 [ 0  1  0  1  0  0  1  1  0  0  1  0  1  0  0  0  1  1  0  1]
 [ 0  0  1  0  0  1  1  0  1  1  0  1  1  0  1  0  0  1  1  1]
 [ 1  1  1  1  1  1  1  0  1  1  1  1  1  1  1  0  0  1  1  1]
 [ 0  1  0  1  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0]
 [ 0  0  0  1  0  0  1  1  1  0  1  0  1  0  1  0  0  1  1 -1]
 [ 0  0  1  1  1  1  0  1  1  0  1  0  1  1  0  0  1  1  0  1]
 [ 1  0  0  0  0  1  0  1  1  1  1  0  1  1  0  0  1  1  1  1]
 [ 1  1  0  0  0  0  0  1  0  1  0  1  0  0  0  1  1  1  0  1]
 [ 1  0  1  0  0  0  0  1  1  1  0 -1  0  1  1  1  0  0  0  0]
 [ 0  1  1  0  1  1  1  0  1  0  0  0  0  1  0  0  1  0  0  1]
 [ 1  0  1  0  1  1  1  1  1  1  1  1  0  1  1  1  0  0  1  1]
 [ 0  0  1  1  1  1  0  1  0  1  0  0  1  1  0  1  0  0  1  0]
 [ 1  0  0  0  0  0  1  1  1  0  1  0  1  0  1  1  0  1  0  0]
 [ 1  1  0  1  0  1  0  1  0  0  0  1  1  1  1  1  0  1  1  0]
 [ 1  1  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0  1

In [4]:
model = model.step()
m2 = model.get_matrix()
model.print_matrix()

[[ 1  0  0  0  0  0  1  0  1  0  1  1  0  1  0  1  0  1  1  1]
 [ 0  1  0  1  0  0  1  1  0  0  1  0  1  0  0  0  1  1  0  1]
 [ 0  0  1  0  0  1  1  0  1  1  0  1  1  0  1  0  0  1  1  1]
 [ 1  1  1  1  1  1  1  0  1  1  1  1  1  1  1  0  0  1  1  1]
 [ 0  1  0  1  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0]
 [ 0  0  0  1  0  0  1  1  1  0  1  0  1  0  1  0  0  1  1  0]
 [ 0  0  1  1  1  1  0  1  1  0  1  0  1  1  0  0  1  1  0  1]
 [ 1  0  0  0  0  1  0  1  1  1  1  0  1  1  0  0  1  1  1  1]
 [ 1  1  0  0  0  0  0  1  0  1  0  1  0  0  0  1  1  1  0  1]
 [ 1  0  1  0  0  0  0  1  1  1  0 -1  0  1  1  1  0  0  0  0]
 [ 0  1  1  0  1  1  1  0  1  0  0  0  0  1  0  0  1  0  0  1]
 [ 1  0  1  0  1  1  1  1  1  1  1  1  0  1  1  1  0  0  1  1]
 [ 0  0  1  1  1  1  0  1  0  1  0  0  1  1  0  1  0  0  1  0]
 [ 1  0  0  0  0  0  1  1  1  0  1  0  1  0  1  1  0  1  0  0]
 [ 1  1  0  1  0  1  0  1  0  0  0  1  1  1  1  1  0  1  1  0]
 [ 1  1  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0  1

In [5]:
print(model.blocked)

False


In [6]:
print(f"dissatisfaction:{model.get_mean_dissatisfaction()}")
print(f"interratial pears: {model.get_mean_interratial_pears()}")
print(f"mean similarity: {model.get_mean_similarity_ratio()}")

dissatisfaction:0.648989898989899
interratial pears: (0.5095785440613027, 0.5082802547770701, 1.0178587988383727)
mean similarity: 0.4898989898989899
